[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://dev-ceoss-backend.herokuapp.com/api"

[context.branch-deploy]
  REACT_APP_API_URL = "https://dev-ceoss-backend.herokuapp.com/api"

[context.production]
  REACT_APP_API_URL = "https://ceoss-backend.herokuapp.com/api"